export interface CountryCode {
  iso: string
  dial: string
  nameZh: string
  nameEn: string
}

const TELEGRAM_ANONYMOUS: CountryCode = {
  iso: 'XT',
  dial: '888',
  nameZh: 'Telegram 匿名号码',
  nameEn: 'Telegram Anonymous',
}

const REAL_COUNTRIES: CountryCode[] = [
  { iso: 'AC', dial: '247', nameZh: '阿森松岛', nameEn: 'Ascension Island' },
  { iso: 'AD', dial: '376', nameZh: '安道尔', nameEn: 'Andorra' },
  { iso: 'AE', dial: '971', nameZh: '阿联酋', nameEn: 'United Arab Emirates' },
  { iso: 'AF', dial: '93', nameZh: '阿富汗', nameEn: 'Afghanistan' },
  { iso: 'AG', dial: '1268', nameZh: '安提瓜和巴布达', nameEn: 'Antigua and Barbuda' },
  { iso: 'AI', dial: '1264', nameZh: '安圭拉', nameEn: 'Anguilla' },
  { iso: 'AL', dial: '355', nameZh: '阿尔巴尼亚', nameEn: 'Albania' },
  { iso: 'AM', dial: '374', nameZh: '亚美尼亚', nameEn: 'Armenia' },
  { iso: 'AO', dial: '244', nameZh: '安哥拉', nameEn: 'Angola' },
  { iso: 'AQ', dial: '672', nameZh: '南极洲', nameEn: 'Antarctica' },
  { iso: 'AR', dial: '54', nameZh: '阿根廷', nameEn: 'Argentina' },
  { iso: 'AS', dial: '1684', nameZh: '美属萨摩亚', nameEn: 'American Samoa' },
  { iso: 'AT', dial: '43', nameZh: '奥地利', nameEn: 'Austria' },
  { iso: 'AU', dial: '61', nameZh: '澳大利亚', nameEn: 'Australia' },
  { iso: 'AW', dial: '297', nameZh: '阿鲁巴', nameEn: 'Aruba' },
  { iso: 'AX', dial: '35818', nameZh: '奥兰群岛', nameEn: 'Åland Islands' },
  { iso: 'AZ', dial: '994', nameZh: '阿塞拜疆', nameEn: 'Azerbaijan' },
  { iso: 'BA', dial: '387', nameZh: '波黑', nameEn: 'Bosnia and Herzegovina' },
  { iso: 'BB', dial: '1246', nameZh: '巴巴多斯', nameEn: 'Barbados' },
  { iso: 'BD', dial: '880', nameZh: '孟加拉国', nameEn: 'Bangladesh' },
  { iso: 'BE', dial: '32', nameZh: '比利时', nameEn: 'Belgium' },
  { iso: 'BF', dial: '226', nameZh: '布基纳法索', nameEn: 'Burkina Faso' },
  { iso: 'BG', dial: '359', nameZh: '保加利亚', nameEn: 'Bulgaria' },
  { iso: 'BH', dial: '973', nameZh: '巴林', nameEn: 'Bahrain' },
  { iso: 'BI', dial: '257', nameZh: '布隆迪', nameEn: 'Burundi' },
  { iso: 'BJ', dial: '229', nameZh: '贝宁', nameEn: 'Benin' },
  { iso: 'BL', dial: '590', nameZh: '圣巴泰勒米', nameEn: 'Saint Barthélemy' },
  { iso: 'BM', dial: '1441', nameZh: '百慕大', nameEn: 'Bermuda' },
  { iso: 'BN', dial: '673', nameZh: '文莱', nameEn: 'Brunei' },
  { iso: 'BO', dial: '591', nameZh: '玻利维亚', nameEn: 'Bolivia' },
  { iso: 'BQ', dial: '599', nameZh: '荷兰加勒比区', nameEn: 'Caribbean Netherlands' },
  { iso: 'BR', dial: '55', nameZh: '巴西', nameEn: 'Brazil' },
  { iso: 'BS', dial: '1242', nameZh: '巴哈马', nameEn: 'Bahamas' },
  { iso: 'BT', dial: '975', nameZh: '不丹', nameEn: 'Bhutan' },
  { iso: 'BW', dial: '267', nameZh: '博茨瓦纳', nameEn: 'Botswana' },
  { iso: 'BY', dial: '375', nameZh: '白俄罗斯', nameEn: 'Belarus' },
  { iso: 'BZ', dial: '501', nameZh: '伯利兹', nameEn: 'Belize' },
  { iso: 'CA', dial: '1', nameZh: '加拿大', nameEn: 'Canada' },
  { iso: 'CC', dial: '61', nameZh: '科科斯（基林）群岛', nameEn: 'Cocos (Keeling) Islands' },
  { iso: 'CD', dial: '243', nameZh: '刚果（金）', nameEn: 'DR Congo' },
  { iso: 'CF', dial: '236', nameZh: '中非共和国', nameEn: 'Central African Republic' },
  { iso: 'CG', dial: '242', nameZh: '刚果（布）', nameEn: 'Republic of the Congo' },
  { iso: 'CH', dial: '41', nameZh: '瑞士', nameEn: 'Switzerland' },
  { iso: 'CI', dial: '225', nameZh: '科特迪瓦', nameEn: "Côte d'Ivoire" },
  { iso: 'CK', dial: '682', nameZh: '库克群岛', nameEn: 'Cook Islands' },
  { iso: 'CL', dial: '56', nameZh: '智利', nameEn: 'Chile' },
  { iso: 'CM', dial: '237', nameZh: '喀麦隆', nameEn: 'Cameroon' },
  { iso: 'CN', dial: '86', nameZh: '中国大陆', nameEn: 'China' },
  { iso: 'CO', dial: '57', nameZh: '哥伦比亚', nameEn: 'Colombia' },
  { iso: 'CR', dial: '506', nameZh: '哥斯达黎加', nameEn: 'Costa Rica' },
  { iso: 'CU', dial: '53', nameZh: '古巴', nameEn: 'Cuba' },
  { iso: 'CV', dial: '238', nameZh: '佛得角', nameEn: 'Cape Verde' },
  { iso: 'CW', dial: '599', nameZh: '库拉索', nameEn: 'Curaçao' },
  { iso: 'CX', dial: '61', nameZh: '圣诞岛', nameEn: 'Christmas Island' },
  { iso: 'CY', dial: '357', nameZh: '塞浦路斯', nameEn: 'Cyprus' },
  { iso: 'CZ', dial: '420', nameZh: '捷克', nameEn: 'Czechia' },
  { iso: 'DE', dial: '49', nameZh: '德国', nameEn: 'Germany' },
  { iso: 'DJ', dial: '253', nameZh: '吉布提', nameEn: 'Djibouti' },
  { iso: 'DK', dial: '45', nameZh: '丹麦', nameEn: 'Denmark' },
  { iso: 'DM', dial: '1767', nameZh: '多米尼克', nameEn: 'Dominica' },
  { iso: 'DO', dial: '1809', nameZh: '多米尼加', nameEn: 'Dominican Republic' },
  { iso: 'DZ', dial: '213', nameZh: '阿尔及利亚', nameEn: 'Algeria' },
  { iso: 'EC', dial: '593', nameZh: '厄瓜多尔', nameEn: 'Ecuador' },
  { iso: 'EE', dial: '372', nameZh: '爱沙尼亚', nameEn: 'Estonia' },
  { iso: 'EG', dial: '20', nameZh: '埃及', nameEn: 'Egypt' },
  { iso: 'EH', dial: '212', nameZh: '西撒哈拉', nameEn: 'Western Sahara' },
  { iso: 'ER', dial: '291', nameZh: '厄立特里亚', nameEn: 'Eritrea' },
  { iso: 'ES', dial: '34', nameZh: '西班牙', nameEn: 'Spain' },
  { iso: 'ET', dial: '251', nameZh: '埃塞俄比亚', nameEn: 'Ethiopia' },
  { iso: 'FI', dial: '358', nameZh: '芬兰', nameEn: 'Finland' },
  { iso: 'FJ', dial: '679', nameZh: '斐济', nameEn: 'Fiji' },
  { iso: 'FK', dial: '500', nameZh: '福克兰群岛', nameEn: 'Falkland Islands' },
  { iso: 'FM', dial: '691', nameZh: '密克罗尼西亚联邦', nameEn: 'Micronesia' },
  { iso: 'FO', dial: '298', nameZh: '法罗群岛', nameEn: 'Faroe Islands' },
  { iso: 'FR', dial: '33', nameZh: '法国', nameEn: 'France' },
  { iso: 'GA', dial: '241', nameZh: '加蓬', nameEn: 'Gabon' },
  { iso: 'GB', dial: '44', nameZh: '英国', nameEn: 'United Kingdom' },
  { iso: 'GD', dial: '1473', nameZh: '格林纳达', nameEn: 'Grenada' },
  { iso: 'GE', dial: '995', nameZh: '格鲁吉亚', nameEn: 'Georgia' },
  { iso: 'GF', dial: '594', nameZh: '法属圭亚那', nameEn: 'French Guiana' },
  { iso: 'GG', dial: '441481', nameZh: '根西岛', nameEn: 'Guernsey' },
  { iso: 'GH', dial: '233', nameZh: '加纳', nameEn: 'Ghana' },
  { iso: 'GI', dial: '350', nameZh: '直布罗陀', nameEn: 'Gibraltar' },
  { iso: 'GL', dial: '299', nameZh: '格陵兰', nameEn: 'Greenland' },
  { iso: 'GM', dial: '220', nameZh: '冈比亚', nameEn: 'Gambia' },
  { iso: 'GN', dial: '224', nameZh: '几内亚', nameEn: 'Guinea' },
  { iso: 'GP', dial: '590', nameZh: '瓜德罗普', nameEn: 'Guadeloupe' },
  { iso: 'GQ', dial: '240', nameZh: '赤道几内亚', nameEn: 'Equatorial Guinea' },
  { iso: 'GR', dial: '30', nameZh: '希腊', nameEn: 'Greece' },
  { iso: 'GT', dial: '502', nameZh: '危地马拉', nameEn: 'Guatemala' },
  { iso: 'GU', dial: '1671', nameZh: '关岛', nameEn: 'Guam' },
  { iso: 'GW', dial: '245', nameZh: '几内亚比绍', nameEn: 'Guinea-Bissau' },
  { iso: 'GY', dial: '592', nameZh: '圭亚那', nameEn: 'Guyana' },
  { iso: 'HK', dial: '852', nameZh: '中国香港', nameEn: 'Hong Kong' },
  { iso: 'HN', dial: '504', nameZh: '洪都拉斯', nameEn: 'Honduras' },
  { iso: 'HR', dial: '385', nameZh: '克罗地亚', nameEn: 'Croatia' },
  { iso: 'HT', dial: '509', nameZh: '海地', nameEn: 'Haiti' },
  { iso: 'HU', dial: '36', nameZh: '匈牙利', nameEn: 'Hungary' },
  { iso: 'ID', dial: '62', nameZh: '印度尼西亚', nameEn: 'Indonesia' },
  { iso: 'IE', dial: '353', nameZh: '爱尔兰', nameEn: 'Ireland' },
  { iso: 'IL', dial: '972', nameZh: '以色列', nameEn: 'Israel' },
  { iso: 'IM', dial: '441624', nameZh: '马恩岛', nameEn: 'Isle of Man' },
  { iso: 'IN', dial: '91', nameZh: '印度', nameEn: 'India' },
  { iso: 'IO', dial: '246', nameZh: '英属印度洋领地', nameEn: 'British Indian Ocean Territory' },
  { iso: 'IQ', dial: '964', nameZh: '伊拉克', nameEn: 'Iraq' },
  { iso: 'IR', dial: '98', nameZh: '伊朗', nameEn: 'Iran' },
  { iso: 'IS', dial: '354', nameZh: '冰岛', nameEn: 'Iceland' },
  { iso: 'IT', dial: '39', nameZh: '意大利', nameEn: 'Italy' },
  { iso: 'JE', dial: '441534', nameZh: '泽西岛', nameEn: 'Jersey' },
  { iso: 'JM', dial: '1876', nameZh: '牙买加', nameEn: 'Jamaica' },
  { iso: 'JO', dial: '962', nameZh: '约旦', nameEn: 'Jordan' },
  { iso: 'JP', dial: '81', nameZh: '日本', nameEn: 'Japan' },
  { iso: 'KE', dial: '254', nameZh: '肯尼亚', nameEn: 'Kenya' },
  { iso: 'KG', dial: '996', nameZh: '吉尔吉斯斯坦', nameEn: 'Kyrgyzstan' },
  { iso: 'KH', dial: '855', nameZh: '柬埔寨', nameEn: 'Cambodia' },
  { iso: 'KI', dial: '686', nameZh: '基里巴斯', nameEn: 'Kiribati' },
  { iso: 'KM', dial: '269', nameZh: '科摩罗', nameEn: 'Comoros' },
  { iso: 'KN', dial: '1869', nameZh: '圣基茨和尼维斯', nameEn: 'Saint Kitts and Nevis' },
  { iso: 'KP', dial: '850', nameZh: '朝鲜', nameEn: 'North Korea' },
  { iso: 'KR', dial: '82', nameZh: '韩国', nameEn: 'South Korea' },
  { iso: 'KW', dial: '965', nameZh: '科威特', nameEn: 'Kuwait' },
  { iso: 'KY', dial: '1345', nameZh: '开曼群岛', nameEn: 'Cayman Islands' },
  { iso: 'KZ', dial: '7', nameZh: '哈萨克斯坦', nameEn: 'Kazakhstan' },
  { iso: 'LA', dial: '856', nameZh: '老挝', nameEn: 'Laos' },
  { iso: 'LB', dial: '961', nameZh: '黎巴嫩', nameEn: 'Lebanon' },
  { iso: 'LC', dial: '1758', nameZh: '圣卢西亚', nameEn: 'Saint Lucia' },
  { iso: 'LI', dial: '423', nameZh: '列支敦士登', nameEn: 'Liechtenstein' },
  { iso: 'LK', dial: '94', nameZh: '斯里兰卡', nameEn: 'Sri Lanka' },
  { iso: 'LR', dial: '231', nameZh: '利比里亚', nameEn: 'Liberia' },
  { iso: 'LS', dial: '266', nameZh: '莱索托', nameEn: 'Lesotho' },
  { iso: 'LT', dial: '370', nameZh: '立陶宛', nameEn: 'Lithuania' },
  { iso: 'LU', dial: '352', nameZh: '卢森堡', nameEn: 'Luxembourg' },
  { iso: 'LV', dial: '371', nameZh: '拉脱维亚', nameEn: 'Latvia' },
  { iso: 'LY', dial: '218', nameZh: '利比亚', nameEn: 'Libya' },
  { iso: 'MA', dial: '212', nameZh: '摩洛哥', nameEn: 'Morocco' },
  { iso: 'MC', dial: '377', nameZh: '摩纳哥', nameEn: 'Monaco' },
  { iso: 'MD', dial: '373', nameZh: '摩尔多瓦', nameEn: 'Moldova' },
  { iso: 'ME', dial: '382', nameZh: '黑山', nameEn: 'Montenegro' },
  { iso: 'MF', dial: '590', nameZh: '法属圣马丁', nameEn: 'Saint Martin' },
  { iso: 'MG', dial: '261', nameZh: '马达加斯加', nameEn: 'Madagascar' },
  { iso: 'MH', dial: '692', nameZh: '马绍尔群岛', nameEn: 'Marshall Islands' },
  { iso: 'MK', dial: '389', nameZh: '北马其顿', nameEn: 'North Macedonia' },
  { iso: 'ML', dial: '223', nameZh: '马里', nameEn: 'Mali' },
  { iso: 'MM', dial: '95', nameZh: '缅甸', nameEn: 'Myanmar' },
  { iso: 'MN', dial: '976', nameZh: '蒙古', nameEn: 'Mongolia' },
  { iso: 'MO', dial: '853', nameZh: '中国澳门', nameEn: 'Macao' },
  { iso: 'MP', dial: '1670', nameZh: '北马里亚纳群岛', nameEn: 'Northern Mariana Islands' },
  { iso: 'MQ', dial: '596', nameZh: '马提尼克', nameEn: 'Martinique' },
  { iso: 'MR', dial: '222', nameZh: '毛里塔尼亚', nameEn: 'Mauritania' },
  { iso: 'MS', dial: '1664', nameZh: '蒙特塞拉特', nameEn: 'Montserrat' },
  { iso: 'MT', dial: '356', nameZh: '马耳他', nameEn: 'Malta' },
  { iso: 'MU', dial: '230', nameZh: '毛里求斯', nameEn: 'Mauritius' },
  { iso: 'MV', dial: '960', nameZh: '马尔代夫', nameEn: 'Maldives' },
  { iso: 'MW', dial: '265', nameZh: '马拉维', nameEn: 'Malawi' },
  { iso: 'MX', dial: '52', nameZh: '墨西哥', nameEn: 'Mexico' },
  { iso: 'MY', dial: '60', nameZh: '马来西亚', nameEn: 'Malaysia' },
  { iso: 'MZ', dial: '258', nameZh: '莫桑比克', nameEn: 'Mozambique' },
  { iso: 'NA', dial: '264', nameZh: '纳米比亚', nameEn: 'Namibia' },
  { iso: 'NC', dial: '687', nameZh: '新喀里多尼亚', nameEn: 'New Caledonia' },
  { iso: 'NE', dial: '227', nameZh: '尼日尔', nameEn: 'Niger' },
  { iso: 'NF', dial: '672', nameZh: '诺福克岛', nameEn: 'Norfolk Island' },
  { iso: 'NG', dial: '234', nameZh: '尼日利亚', nameEn: 'Nigeria' },
  { iso: 'NI', dial: '505', nameZh: '尼加拉瓜', nameEn: 'Nicaragua' },
  { iso: 'NL', dial: '31', nameZh: '荷兰', nameEn: 'Netherlands' },
  { iso: 'NO', dial: '47', nameZh: '挪威', nameEn: 'Norway' },
  { iso: 'NP', dial: '977', nameZh: '尼泊尔', nameEn: 'Nepal' },
  { iso: 'NR', dial: '674', nameZh: '瑙鲁', nameEn: 'Nauru' },
  { iso: 'NU', dial: '683', nameZh: '纽埃', nameEn: 'Niue' },
  { iso: 'NZ', dial: '64', nameZh: '新西兰', nameEn: 'New Zealand' },
  { iso: 'OM', dial: '968', nameZh: '阿曼', nameEn: 'Oman' },
  { iso: 'PA', dial: '507', nameZh: '巴拿马', nameEn: 'Panama' },
  { iso: 'PE', dial: '51', nameZh: '秘鲁', nameEn: 'Peru' },
  { iso: 'PF', dial: '689', nameZh: '法属波利尼西亚', nameEn: 'French Polynesia' },
  { iso: 'PG', dial: '675', nameZh: '巴布亚新几内亚', nameEn: 'Papua New Guinea' },
  { iso: 'PH', dial: '63', nameZh: '菲律宾', nameEn: 'Philippines' },
  { iso: 'PK', dial: '92', nameZh: '巴基斯坦', nameEn: 'Pakistan' },
  { iso: 'PL', dial: '48', nameZh: '波兰', nameEn: 'Poland' },
  { iso: 'PM', dial: '508', nameZh: '圣皮埃尔和密克隆', nameEn: 'Saint Pierre and Miquelon' },
  { iso: 'PR', dial: '1787', nameZh: '波多黎各', nameEn: 'Puerto Rico' },
  { iso: 'PS', dial: '970', nameZh: '巴勒斯坦', nameEn: 'Palestine' },
  { iso: 'PT', dial: '351', nameZh: '葡萄牙', nameEn: 'Portugal' },
  { iso: 'PW', dial: '680', nameZh: '帕劳', nameEn: 'Palau' },
  { iso: 'PY', dial: '595', nameZh: '巴拉圭', nameEn: 'Paraguay' },
  { iso: 'QA', dial: '974', nameZh: '卡塔尔', nameEn: 'Qatar' },
  { iso: 'RE', dial: '262', nameZh: '留尼汪', nameEn: 'Réunion' },
  { iso: 'RO', dial: '40', nameZh: '罗马尼亚', nameEn: 'Romania' },
  { iso: 'RS', dial: '381', nameZh: '塞尔维亚', nameEn: 'Serbia' },
  { iso: 'RU', dial: '7', nameZh: '俄罗斯', nameEn: 'Russia' },
  { iso: 'RW', dial: '250', nameZh: '卢旺达', nameEn: 'Rwanda' },
  { iso: 'SA', dial: '966', nameZh: '沙特阿拉伯', nameEn: 'Saudi Arabia' },
  { iso: 'SB', dial: '677', nameZh: '所罗门群岛', nameEn: 'Solomon Islands' },
  { iso: 'SC', dial: '248', nameZh: '塞舌尔', nameEn: 'Seychelles' },
  { iso: 'SD', dial: '249', nameZh: '苏丹', nameEn: 'Sudan' },
  { iso: 'SE', dial: '46', nameZh: '瑞典', nameEn: 'Sweden' },
  { iso: 'SG', dial: '65', nameZh: '新加坡', nameEn: 'Singapore' },
  { iso: 'SH', dial: '290', nameZh: '圣赫勒拿', nameEn: 'Saint Helena' },
  { iso: 'SI', dial: '386', nameZh: '斯洛文尼亚', nameEn: 'Slovenia' },
  { iso: 'SK', dial: '421', nameZh: '斯洛伐克', nameEn: 'Slovakia' },
  { iso: 'SL', dial: '232', nameZh: '塞拉利昂', nameEn: 'Sierra Leone' },
  { iso: 'SM', dial: '378', nameZh: '圣马力诺', nameEn: 'San Marino' },
  { iso: 'SN', dial: '221', nameZh: '塞内加尔', nameEn: 'Senegal' },
  { iso: 'SO', dial: '252', nameZh: '索马里', nameEn: 'Somalia' },
  { iso: 'SR', dial: '597', nameZh: '苏里南', nameEn: 'Suriname' },
  { iso: 'SS', dial: '211', nameZh: '南苏丹', nameEn: 'South Sudan' },
  { iso: 'ST', dial: '239', nameZh: '圣多美和普林西比', nameEn: 'São Tomé and Príncipe' },
  { iso: 'SV', dial: '503', nameZh: '萨尔瓦多', nameEn: 'El Salvador' },
  { iso: 'SX', dial: '1721', nameZh: '荷属圣马丁', nameEn: 'Sint Maarten' },
  { iso: 'SY', dial: '963', nameZh: '叙利亚', nameEn: 'Syria' },
  { iso: 'SZ', dial: '268', nameZh: '斯威士兰', nameEn: 'Eswatini' },
  { iso: 'TC', dial: '1649', nameZh: '特克斯和凯科斯群岛', nameEn: 'Turks and Caicos Islands' },
  { iso: 'TD', dial: '235', nameZh: '乍得', nameEn: 'Chad' },
  { iso: 'TG', dial: '228', nameZh: '多哥', nameEn: 'Togo' },
  { iso: 'TH', dial: '66', nameZh: '泰国', nameEn: 'Thailand' },
  { iso: 'TJ', dial: '992', nameZh: '塔吉克斯坦', nameEn: 'Tajikistan' },
  { iso: 'TK', dial: '690', nameZh: '托克劳', nameEn: 'Tokelau' },
  { iso: 'TL', dial: '670', nameZh: '东帝汶', nameEn: 'Timor-Leste' },
  { iso: 'TM', dial: '993', nameZh: '土库曼斯坦', nameEn: 'Turkmenistan' },
  { iso: 'TN', dial: '216', nameZh: '突尼斯', nameEn: 'Tunisia' },
  { iso: 'TO', dial: '676', nameZh: '汤加', nameEn: 'Tonga' },
  { iso: 'TR', dial: '90', nameZh: '土耳其', nameEn: 'Turkey' },
  { iso: 'TT', dial: '1868', nameZh: '特立尼达和多巴哥', nameEn: 'Trinidad and Tobago' },
  { iso: 'TV', dial: '688', nameZh: '图瓦卢', nameEn: 'Tuvalu' },
  { iso: 'TW', dial: '886', nameZh: '中国台湾', nameEn: 'Taiwan' },
  { iso: 'TZ', dial: '255', nameZh: '坦桑尼亚', nameEn: 'Tanzania' },
  { iso: 'UA', dial: '380', nameZh: '乌克兰', nameEn: 'Ukraine' },
  { iso: 'UG', dial: '256', nameZh: '乌干达', nameEn: 'Uganda' },
  { iso: 'US', dial: '1', nameZh: '美国', nameEn: 'United States' },
  { iso: 'UY', dial: '598', nameZh: '乌拉圭', nameEn: 'Uruguay' },
  { iso: 'UZ', dial: '998', nameZh: '乌兹别克斯坦', nameEn: 'Uzbekistan' },
  { iso: 'VA', dial: '379', nameZh: '梵蒂冈', nameEn: 'Vatican City' },
  { iso: 'VC', dial: '1784', nameZh: '圣文森特和格林纳丁斯', nameEn: 'Saint Vincent and the Grenadines' },
  { iso: 'VE', dial: '58', nameZh: '委内瑞拉', nameEn: 'Venezuela' },
  { iso: 'VG', dial: '1284', nameZh: '英属维尔京群岛', nameEn: 'British Virgin Islands' },
  { iso: 'VI', dial: '1340', nameZh: '美属维尔京群岛', nameEn: 'U.S. Virgin Islands' },
  { iso: 'VN', dial: '84', nameZh: '越南', nameEn: 'Vietnam' },
  { iso: 'VU', dial: '678', nameZh: '瓦努阿图', nameEn: 'Vanuatu' },
  { iso: 'WF', dial: '681', nameZh: '瓦利斯和富图纳', nameEn: 'Wallis and Futuna' },
  { iso: 'WS', dial: '685', nameZh: '萨摩亚', nameEn: 'Samoa' },
  { iso: 'XK', dial: '383', nameZh: '科索沃', nameEn: 'Kosovo' },
  { iso: 'YE', dial: '967', nameZh: '也门', nameEn: 'Yemen' },
  { iso: 'YT', dial: '262', nameZh: '马约特', nameEn: 'Mayotte' },
  { iso: 'ZA', dial: '27', nameZh: '南非', nameEn: 'South Africa' },
  { iso: 'ZM', dial: '260', nameZh: '赞比亚', nameEn: 'Zambia' },
  { iso: 'ZW', dial: '263', nameZh: '津巴布韦', nameEn: 'Zimbabwe' },
]

const zhCollator = new Intl.Collator('zh-Hans-CN', { sensitivity: 'base' })
export const COUNTRIES: CountryCode[] = [
  TELEGRAM_ANONYMOUS,
  ...REAL_COUNTRIES.slice().sort((a, b) => zhCollator.compare(a.nameZh, b.nameZh)),
]

export const DEFAULT_COUNTRY: CountryCode =
  REAL_COUNTRIES.find((c) => c.iso === 'CN') ?? (COUNTRIES[0] as CountryCode)

export function flagEmoji(iso: string): string {
  if (iso === 'XT') return '🌐'
  if (iso.length !== 2) return '🏳️'
  const codePoints = iso
    .toUpperCase()
    .split('')
    .map((c) => 0x1f1e6 + (c.charCodeAt(0) - 'A'.charCodeAt(0)))
  return String.fromCodePoint(...codePoints)
}

export function searchCountries(query: string): CountryCode[] {
  const q = query.trim().toLowerCase()
  if (!q) return COUNTRIES
  const qNoPlus = q.startsWith('+') ? q.slice(1) : q
  return COUNTRIES.filter(
    (c) =>
      c.nameZh.toLowerCase().includes(q) ||
      c.nameEn.toLowerCase().includes(q) ||
      c.dial.includes(qNoPlus) ||
      c.iso.toLowerCase().includes(q),
  )
}
